supermarket/sistema/urls.py
from django.urls import path

from .views import *

app_name = 'sistema'
urlpatterns = [
    path("", index, name="index"),
    path("registro/cliente/", registroCliente, name="registro_cliente"),
    path("agregar/carrito/", agregarCarrito, name="agregar_carrito"),    
    path("carrito/", carrito, name="carrito"),    
    path("carrito/cancelar/", cancelarCarrito, name="cancelar_carrito"),    
    path("mis_compras/", verMisCompras, name="mis_compras"),    
    path("facturas/", verFacturas, name="facturas"),    
    path("deudas/", verDeudas, name="deudas"),    

]

supermarket/supermarket/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from .views import *

urlpatterns = [
    path('', index , name='index'),
    path('login/', loginUser, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('datos_iniciales/', cargaDatosInicial, name="datos_iniciales"),
    path('admin/', admin.site.urls),
    path("sistema/", include("sistema.urls")),        
    # re_path(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], protected_serve, {'document_root': settings.MEDIA_ROOT}),     
]

supermarket/templates/cliente/carrito.html
{% extends 'base.html' %}


{% block main_content %}  
<br>
<form method="POST">
    {% csrf_token %}
    <div class = "col-sm-12">
        <div class = "card">                        
            <div class="card-header text-center">          
                <h4 class="card-title "><strong>Productos </strong></h4>                    
            </div>            
            
            {% if compra %}
            <div class="card-body">     
                <div class="text-center">
                    <p class="text=center"><strong>Detalle de pago</strong></p>
                </div>
                
                <div class="form-group">
                    <label for="moneda">Moneda</label>
                    <select class="form-control" id="moneda" name='moneda'>
                        {% for value in moneda %}
                        <option value="{{value.id}}" >{{value.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="forma_pago">Forma pago</label>
                    <select class="form-control" id="forma_pago" name='forma_pago'>
                        {% for value in forma_pago %}
                        <option value="{{value.id}}" >{{value.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="metodo_pago">Metodo Pago</label>
                    <select class="form-control" id="metodo_pago" name='metodo_pago'>
                        {% for value in metodo_pago %}
                        <option value="{{value.id}}" >{{value.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                <hr>
                <br>
                <table class="table table-striped">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">subtotal</th>
                        <th scope="col">impuesto</th>
                        <th scope="col">total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in compra %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{producto.nombre}}</td>
                                <td> {{producto.cantidad|floatformat}}</td>
                                <td>$ {{producto.subtotal|floatformat}} </td>
                                <td>$ {{producto.impuesto|floatformat}} </td>
                                <td>$ {{producto.total|floatformat}} </td>
                            </tr>        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <hr>
            <br>

            <div class = "row">
                <div class = "col-12 col-sm-6 col-md-6">                
                </div>
                <div class = "col-12 col-sm-6 col-md-6">
                    <div class="form-group row">
                        <label for="cantidad_global" class="col-sm-6 col-form-label">Piezas Totales</label>
                        <div class="col-sm-6">
                        <input type="text" readonly class="form-control-plaintext" id="cantidad_global" value="{{cantidad_global|floatformat}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="subtotal_global" class="col-sm-6 col-form-label">Subtotal</label>
                        <div class="col-sm-6">
                        <input type="text" readonly class="form-control-plaintext" id="subtotal_global" value="$ {{subtotal_global|floatformat}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="impuesto_global" class="col-sm-6 col-form-label">Impuestos</label>
                        <div class="col-sm-6">
                        <input type="text" readonly class="form-control-plaintext" id="impuesto_global" value="$ {{impuesto_global|floatformat}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="total_global" class="col-sm-6 col-form-label">Total</label>
                        <div class="col-sm-6">
                        <input type="text" readonly class="form-control-plaintext" id="total_global" value="$ {{total_global|floatformat}}">
                        </div>
                    </div>
                </div>
            </div>
            

            <div class="card-footer text-muted">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Comprar</button>
                <br>
                <a href="{% url 'sistema:cancelar_carrito' %}" class="btn btn-danger btn-lg  btn-block" role="button">Cancelar</a>
            </div>            
            
            {% else %}
            <div class="card-body">     
                <div class="text-center">
                    <p> Sin productos en el carrito. </p>
                </div>
            </div>
            {% endif %}  
        </div>
    </div>  

</form>

<br>
<br>
<br>
<br>
<br>
<br>


{% endblock %}

supermarket/templates/cliente/comprar_productos.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}  

    <div class = "row"></div>

    <form method="POST">
        {% csrf_token %}    
        <div class = "col-sm-12">
            <div class = "card">                        
                <div class="card-header text-center">          
                    <h4 class="card-title "><strong>Productos </strong></h4>                    
                </div>            
                <div class="card-body">                   
                    
                    {% if productos %}
                        <div class="row">
                        {% for producto in productos %}
                                <div class = "col-12 col-sm-4 col-md-4">
                                    <div class="card text-white bg-info" style="width: 18rem;">
                                        <img class="card-img-top img-thumbnail" src="{% static 'img/noimage.png' %}" alt="Nombre_Producto">
                                        <div class="card-body">
                                            <h5 class="card-title">{{producto.nombre}}</h5>
                                            <p class="card-text">{{producto.descripcion}}</p>
                                            <p class="card-text">Precio: ${{producto.precio_publico}}</p>
                                            <div class="form-group row">    
                                                <label for="producto_{{producto.id}}" class="col-sm-6 col-form-label">Cantidad:</label>
                                                <div class="col-sm-6">                                                
                                                    <input type="number" class="form-control" id="producto_{{producto.id}}" name="producto_{{producto.id}}" value=0>
                                                </div>
                                            </div>                      
                                        </div>
                                    </div>
                                </div>                             
                            {% if forloop.counter|divisibleby:3 %}
                        </div>
                        <br>
                        <div class="row">
                            
                            {% endif %}
                        {% endfor %}
                        </div>
                    {% endif %}  
                    
                </div>
                <div class="card-footer text-muted">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Agregar</button>                    
                </div>
            </div>
        </div>  
    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

supermarket/templates/cliente/index.html
{% extends 'base.html' %}


{% block main_content %}  
  
  <div class = "row"></div>

  <div class = "col-sm-12">
    <div class = "card">                        
      <div class="card-header text-center">          
          <h4 class="card-title "><strong>PrimeMed Supply </strong></h4>
          <h6 class="card-subtitle mb-2 text-muted">"Salud en cada entrega!"</h6>
          <p class="card-text"></p>
        </div>            
        
      </div>
  </div>  

{% endblock %}

supermarket/templates/cliente/lista_compras.html
{% extends 'base.html' %}

{% block main_content %}
    <div class = "row">
        <div class = "col-sm-12">
            <div class = "card">                        
                <div class="card-header text-center">
                    <h5>
                        Lista de ultimas <span class="text-success">COMPRAS</span>
                    </h5>                        
                </div>            
                <div class = "card-body">
                    <div class="table-responsive">
                        <table id = 'tabla-compras' style="width:100%" class="table">
                            <thead>
                                <tr class="text-center">
                                    <th scope='col'> # </th>
                                    <th scope='col'> Fecha </th>
                                    <th scope='col'> Total Pzas </th>
                                    <th scope='col'> Subtotal </th>
                                    <th scope='col'> Impuesto </th>
                                    <th scope='col'> Total </th>
                                    <th scope='col'> Moneda </th>                                    
                                    <th scope='col'> Forma Pago</th>
                                    <th scope='col'> Metodo Pago</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% if compras %}
                                    {% for compra in compras %}
                                        <tr class="text-center">
                                            <th scope="row"><small>{{forloop.counter}}</small></th>
                                            <td> {{compra.fecha}}</td>
                                            <td> {{compra.total_piezas}}</td>
                                            <td>$ {{compra.subtotal|floatformat}}</td>
                                            <td>$ {{compra.impuesto|floatformat}}</td>
                                            <td>$ {{compra.total|floatformat}}</td>
                                            <td> {{compra.moneda}}</td>
                                            <td> {{compra.forma_pago}}</td>                                                                               
                                            <td> {{compra.metodo_pago}}</td>                                                                               
                                        </tr>
                                    {% endfor %}
                                
                                {% endif %}
                            </tbody>
                        </table>
                        
                    </div>                
                    <hr>
                        
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#tabla-compras').dataTable({
                "scrollX": true,
                dom: "<'form-group row'<'mx-auto'B> <'mx-auto'l> <'mx-auto'f>>" +
                "<'wrapper'<'mx-auto'rt>>" +
                "<'form-group row'<'mx-auto'i><'mx-auto'p>>",                
                buttons: [
                    {extend: 'colvis', text: 'Mostrar'},
                    {extend: 'pdfHtml5', text: 'PDF', exportOptions: {columns: ':visible'}},
                    {extend: 'excel', text: 'Excel', exportOptions: {columns: ':visible'}},
                    {extend: 'print', text: 'Imprimir', exportOptions: {columns: ':visible'}}
                ],
                "order": [[0, "asc"]],
                "lengthMenu": [5, 10, 25, 50, 75, 100],                
                "language": {
                    "decimal": "",
                    "emptyTable": "No hay datos disponibles en la tabla",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando del 0 al 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ entradas.  ",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "colvis": "columna visible",
                    "zeroRecords": "No se encontraron registros",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
    
{% endblock %}

 

supermarket/templates/cliente/lista_deudas.html
{% extends 'base.html' %}

{% block main_content %}
    <div class = "row">
        <div class = "col-sm-12">
            <div class = "card">                        
                <div class="card-header text-center">
                    <h5>
                        Lista de <span class="text-danger">DEUDAS</span>
                    </h5>                        
                </div>            
                <div class = "card-body">
                    <div class="table-responsive">
                        <table id = 'tabla-deudas' style="width:100%" class="table">
                            <thead>
                                <tr class="text-center">
                                    <th scope='col'> # </th>
                                    <th scope='col'> Compra ID </th>
                                    <th scope='col'> Fecha Compra </th>
                                    <th scope='col'> Total </th>
                                    <th scope='col'> Fecha Limite </th>                                    
                                </tr>
                            </thead>

                            <tbody>
                                {% if deudas %}
                                    {% for deuda in deudas %}
                                        <tr class="text-center">
                                            <th scope="row"><small>{{forloop.counter}}</small></th>
                                            <td> {{deuda.pk}}</td>                                            
                                            <td> {{deuda.venta.fecha}}</td>
                                            <td>$ {{deuda.total}}</td>
                                            <td> {{deuda.fecha_limite}}</td>
                                        </tr>
                                    {% endfor %}
                                
                                {% endif %}
                            </tbody>
                        </table>
                        
                    </div>                
                    <hr>
                        
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#tabla-deudas').dataTable({
                "scrollX": true,
                dom: "<'form-group row'<'mx-auto'B> <'mx-auto'l> <'mx-auto'f>>" +
                "<'wrapper'<'mx-auto'rt>>" +
                "<'form-group row'<'mx-auto'i><'mx-auto'p>>",                
                buttons: [
                    {extend: 'colvis', text: 'Mostrar'},
                    {extend: 'pdfHtml5', text: 'PDF', exportOptions: {columns: ':visible'}},
                    {extend: 'excel', text: 'Excel', exportOptions: {columns: ':visible'}},
                    {extend: 'print', text: 'Imprimir', exportOptions: {columns: ':visible'}}
                ],
                "order": [[0, "asc"]],
                "lengthMenu": [5, 10, 25, 50, 75, 100],                
                "language": {
                    "decimal": "",
                    "emptyTable": "No hay datos disponibles en la tabla",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando del 0 al 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ entradas.  ",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "colvis": "columna visible",
                    "zeroRecords": "No se encontraron registros",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
    
{% endblock %}

 

supermarket/templates/cliente/lista_facturas.html
{% extends 'base.html' %}

{% block main_content %}
    <div class = "row">
        <div class = "col-sm-12">
            <div class = "card">                        
                <div class="card-header text-center">
                    <h5>
                        Lista de <span class="text-primary">FACTURAS</span>
                    </h5>                        
                </div>            
                <div class = "card-body">
                    <div class="table-responsive">
                        <table id = 'tabla-facturas' style="width:100%" class="table">
                            <thead>
                                <tr class="text-center">
                                    <th scope='col'> # </th>
                                    <th scope='col'> Fecha Compra </th>
                                    <th scope='col'> Fecha Factura </th>
                                    <th scope='col'> Total </th>                                    
                                </tr>
                            </thead>

                            <tbody>
                                {% if facturas %}
                                    {% for factura in facturas %}
                                        <tr class="text-center">
                                            <th scope="row"><small>{{forloop.counter}}</small></th>
                                            <td> {{factura.venta.fecha}}</td>
                                            <td> {{factura.fecha}}</td>
                                            <td>$ {{factura.venta.total}}</td>                                                 
                                        </tr>
                                    {% endfor %}                                
                                {% endif %}
                            </tbody>
                        </table>
                        
                    </div>                
                    <hr>
                        
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#tabla-facturas').dataTable({
                "scrollX": true,
                dom: "<'form-group row'<'mx-auto'B> <'mx-auto'l> <'mx-auto'f>>" +
                "<'wrapper'<'mx-auto'rt>>" +
                "<'form-group row'<'mx-auto'i><'mx-auto'p>>",                
                buttons: [
                    {extend: 'colvis', text: 'Mostrar'},
                    {extend: 'pdfHtml5', text: 'PDF', exportOptions: {columns: ':visible'}},
                    {extend: 'excel', text: 'Excel', exportOptions: {columns: ':visible'}},
                    {extend: 'print', text: 'Imprimir', exportOptions: {columns: ':visible'}}
                ],
                "order": [[0, "asc"]],
                "lengthMenu": [5, 10, 25, 50, 75, 100],                
                "language": {
                    "decimal": "",
                    "emptyTable": "No hay datos disponibles en la tabla",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando del 0 al 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ entradas.  ",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "colvis": "columna visible",
                    "zeroRecords": "No se encontraron registros",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
    
{% endblock %}

 