supermarket/sistema/urls.py
from django.urls import path

from .views import *

app_name = 'sistema'
urlpatterns = [
    path("", index, name="index"),
    path("registro/cliente/", registroCliente, name="registro_cliente"),
    path("agregar/carrito/", agregarCarrito, name="agregar_carrito"),    
    path("carrito/", carrito, name="carrito"),    
    path("carrito/cancelar/", cancelarCarrito, name="cancelar_carrito"),    
    path("mis_compras/", verMisCompras, name="mis_compras"),    
    path("facturas/", verFacturas, name="facturas"),    
    path("deudas/", verDeudas, name="deudas"),    

]

supermarket/supermarket/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from .views import *

urlpatterns = [
    path('', index , name='index'),
    path('login/', loginUser, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('datos_iniciales/', cargaDatosInicial, name="datos_iniciales"),
    path('admin/', admin.site.urls),
    path("sistema/", include("sistema.urls")),        
    # re_path(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], protected_serve, {'document_root': settings.MEDIA_ROOT}),     
]

supermarket/templates/base.html
{% load static %}

<!doctype html>
<html lang="es">    
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta  name="description" content="Inicia sesión en nuestra plataforma para acceder a tu cuenta y disfrutar de todos nuestros servicios.">
        <meta name="author" content="Ayala Canul Emiliano">
        <title>PrimeMed Supply</title>
        <!--<link rel="icon" href="{% static 'img/SICAAD2.png' %}">-->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link href="{% static 'css/datatables.bootstrap4.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/responsive.bootstrap4.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/pnotify.custom.min.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'css/fontawesome.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'css/tempusdominus.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'materialdesign-icons/css/materialdesignicons.min.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'css/animate.min.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'css/precedentes.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'css/quill.snow.css' %}" rel="stylesheet">    

        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/popper_bt4.js' %}"></script>
        <script src="{% static 'js/datatables.min.js' %}"></script>
        <script src="{% static 'js/pnotify.custom.min.js' %}"></script>
        <script src="{% static 'js/moment.js' %}"></script>
        <script src="{% static 'js/tempusdominus.js' %}"></script>
        <script src="{% static 'js/es.js' %}"></script>
        <script src="{% static 'js/html2canvas.min.js' %}"></script>
        <script src="{% static 'js/jspdf.min.js' %}"></script>
        <script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script>        
        <script src="{% static 'js/quill.js' %}" rel="stylesheet"></script>
    </head>
    
    <body>
        <script>
            class Alerta{        
                constructor(tipo, titulo, texto){        
                    this.tipo = tipo;
                    this.titulo = titulo;
                    this.texto = texto;        
                    this.showAlerta();
                }

                showAlerta(){        
                    if(this.tipo == Alerta.SUCCESS || this.tipo === Alerta.ERROR || this.tipo === Alerta.WARNING || this.tipo === Alerta.INFO){
                        let le_titulo = this.titulo;
                        let le_texto = this.texto;
                        let le_tipo = this.tipo;                        
                        let tiempo_delay = 7500;

                            if(this.tipo == Alerta.SUCCESS){
                                tiempo_delay = 5500;
                            }else if(this.tipo == Alerta.INFO){
                                tiempo_delay = 10000;            
                            }else if(this.tipo == Alerta.WARNING){
                                tiempo_delay = 15000;                
                            }else if(this.tipo == Alerta.ERROR){
                                tiempo_delay = 20000;
                            }  

                        $(function(){                
                            new PNotify({                      
                                title: le_titulo,
                                text: le_texto,
                                styling: 'bootstrap3',
                                type: le_tipo,
                                delay: tiempo_delay,
                            });    
                        });
                    }else{
                        alert(this.titulo + ': ' + this.texto);
                    }
                }

                show(){
                    this.showAlerta();
                }
            }
            Alerta.SUCCESS = 'success';
            Alerta.ERROR = 'error';
            Alerta.WARNING = 'warning';
            Alerta.INFO = 'info';
        </script>
        <script type="text/javascript">        
            {% if messages %} {# Cuando proviene del servidor #}
                {% for message in messages %}                
                    {% if message.level_tag == 'error' %}                          
                        new Alerta(Alerta.ERROR, '{{message.message}}', '{{message.extra_tags}}');
                    {% elif message.level_tag == 'success'%}
                        new Alerta(Alerta.SUCCESS, '{{message.message}}', '{{message.extra_tags}}');
                    {% elif message.level_tag == 'warning'%}
                        new Alerta(Alerta.WARNING, '{{message.message}}', '{{message.extra_tags}}');
                    {% elif message.level_tag == 'info'%}
                        new Alerta(Alerta.INFO, '{{message.message}}', '{{message.extra_tags}}');
                    {% else %}            
                        new Alerta(Alerta.INFO, 'DEV: {{message.message}}', '{{message.extra_tags}}');
                    {% endif %}
                {% endfor %}        
            {% endif %}
        </script>

        <header>
            <!-- top navigation -->        
            {% block topbar %}
                {# Por defecto barra de menu vacía #}
                {% include "topbar.html" %}
            {% endblock %}
            <!-- /top navigation -->        
           
        </header>                        

        <main role="main" style="padding-top: 20px;">
            {% block full_content %}
            <div class="container">
               
                

                {% block main_content %}{% endblock %}
                <!-- /main-content -->
                 
            </div>                
            {% endblock %}
        </main>           
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <!--fixed-bottom-->
        <footer class="bg-light">            
            <div class="container d-none d-md-block">
                <div class="row">
                    <div class="col-md-4">
                        <h4>Nuestro Supermercado</h4>
                        <p>Tu destino para productos frescos y de calidad a precios increíbles.</p>
                        <p>Dirección: 123 Calle Principal, Ciudad Ficticia, CP 12345</p>
                    </div>
                    <div class="col-md-4">
                        <h4>Enlaces Útiles</h4>
                        <ul>
                            <li><a href="#">Términos y Condiciones</a></li>
                            <li><a href="#">Política de Privacidad</a></li>
                            <li><a href="#">Contáctanos</a></li>
                            <li><a href="#">Preguntas Frecuentes</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h4>¡Conéctate con Nosotros!</h4>
                        <ul class="social-icons">
                            <li><a href="#"><i class="mdi mdi-facebook"></i></a></li>
                            <li><a href="#"><i class="mdi mdi-twitter"></i></a></li>
                            <li><a href="#"><i class="mdi mdi-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="bottom-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <p>© 2024 PrimeMed Supply. Todos los derechos reservados.</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </body>
</html>

supermarket/templates/index.html
{% extends 'base.html' %}


{% block main_content %}  
  <div class = "row"></div>
  <div class = "col-sm-12">
    <div class = "card">                        
      <div class="card-header text-center">          
          <h4 class="card-title "><strong>PrimeMed Supply </strong></h4>
          <h6 class="card-subtitle mb-2 text-muted">"Salud en cada entrega!"</h6>
          <p class="card-text"></p>
        </div>            
        <div class = "card-body">
          <div class="text-center">
            <h6>
              Inicie sesión para ver los productos y realizar las compras.
            </h6>                        
          </div>
          <br>
          {% comment %} <div class="text-justify"> <p></p> <br> </div> {% endcomment %}
        </div>
      </div>
  </div>  


{% endblock %}

supermarket/templates/topbar.html
{% load static %}


<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
  
  <div class="container">      
    {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'sistema:index' %}">
        <img src="{% static 'img/prime_med_supply_logo.png' %}" width="50" height="50" alt="Poder Judicial" style="vertical-align: bottom;">
        <div class="text-center" style="padding-left: 10px; padding-right: 10px; border-right: solid 1px lightgray; display: inline-block;">
          <strong>PrimeMed <br> Supply </strong>
        </div>
      </a>
    {% else %}
      
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'img/prime_med_supply_logo.png' %}" width="50" height="50" alt="Poder Judicial" style="vertical-align: bottom;">
        <div class="text-center" style="padding-left: 10px; padding-right: 10px; border-right: solid 1px lightgray; display: inline-block;">
          <strong>PrimeMed <br> Supply </strong>
        </div>
      </a>
    {% endif %}
    

    <!--BOTÓN DE COLAPSADO-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".colpsadoDoble" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!--MENÚ CENTRAL-->
    <div class="collapse navbar-collapse colpsadoDoble">
      <ul class="navbar-nav mr-auto">        
        {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'sistema:mis_compras' %}">
                <i class="mdi mdi-clipboard" style="font-size: 24px; vertical-align: middle;"></i>
                Mis Compras
            </a>
          </li>  
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sistema:facturas' %}">
                <i class="mdi mdi-file" style="font-size: 24px; vertical-align: middle;"></i>
                Facturas
            </a>
          </li>        

          <li class="nav-item">
            <a class="nav-link" href="{% url 'sistema:deudas' %}">
                <i class="mdi mdi-cash" style="font-size: 24px; vertical-align: middle;"></i>
                Deudas
            </a>
          </li>        
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sistema:agregar_carrito' %}">
                <i class="mdi mdi-shopping" style="font-size: 24px; vertical-align: middle;"></i>
                Comprar
            </a>
          </li>        
                
          
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">          
                <i class="mdi mdi-login" style="font-size: 24px; vertical-align: middle;"></i>
                Login
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sistema:registro_cliente' %}">          
                <i class="mdi mdi-account-plus" style="font-size: 24px; vertical-align: middle;"></i>
                Rergistrarse
            </a>
          </li>
          
        {% endif %}
      </ul>  
    </div>

    
    
    {% block right_menu %}            
      <!--MENÚ DERECHO-->
      {% if user.is_authenticated %}
        <div class="collapse navbar-collapse colpsadoDoble">
          <ul class="navbar-nav ml-auto">
            <!--Volver al menú de aplicaciones-->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sistema:carrito' %}">
                  <i class="mdi mdi-cart-outline" style="font-size: 24px; vertical-align: middle;"></i>
                  Carrito
              </a>
            </li> 
            <li class="nav-item dropdown" style="text-align: right;">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">                
                <strong>Cliente: </strong>
                  <br>
                <strong>
                  {{user.first_name|upper}} {{user.last_name|upper}}
                </strong>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'logout' %}">            
                  <small style = "padding-right: 5px; display: inline-block;" class = "text-center">
                    <div>CERRAR SESIÓN</div>
                  </small>
                  <i class = "mdi mdi-backburger" style="font-size: 28px"></i> 
                </a>
              </div>
            </li>
          </ul>        
        </div>       
      {% endif %} 
    {% endblock %}  
    
  </div>
</nav>